gradient fix for some of them. should look much better now
blazium-engine/blazium-assets pull request #33
Opened 2024-11-16 21:30 UTC by verypleasentusername

2024-11-16 21:31 UTC, verypleasentusername commented
the amount of commits is emberassing....

2024-11-17 08:59 UTC, Captain-Wet-Beard requested changes
If this is going in EngineAssets you may want to run it through SVGO 1st because of the engine's file size checks

2024-11-17 23:36 UTC, Captain-Wet-Beard commented
![icon](https://github.com/user-attachments/assets/aa34a6a0-8976-450d-9c83-1f7e3bee4f62)
![icon_outlined](https://github.com/user-attachments/assets/61b61a6e-f457-4d77-9f7a-2c98f9fb79dc)

Here you go, I ran these through SVGO for you. Just update your PR with these if you don't mind

2024-11-18 00:19 UTC, Bioblaze approved these changes

2024-11-18 00:19 UTC, merged